---

- hosts: webserver
  remote_user: centos
  become: yes
  become_method: sudo
  tasks:
        - name: Install package yum-utils
          yum:
                  name: yum-utils
        - name: Install package device-mapper-persistent-data
          yum:
                  name: device-mapper-persistent-data
        - name: Install package lvm2
          yum:
                  name: lvm2
        - name: adding repo
          shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo          
        - name: Install Docker
          yum:
                  name:
                          - docker-ce
        - name: start daemon
          shell: systemctl start docker 
